language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: QyClDXIZjrU4ulakq/oetI0frJzw2nuhM9nwFSyh3i2wAImr9dB8RDyfdXAOT8Phm14q2NQTrUNCkROcmfjiL7zw9hKX/jp2YU7VSMZtC754nO1h4J3/5rkWhYeojO6poiOjm0KEluAAXZ8CkjLWdgGD3/4FreI6ei2DLiPL4s6LAKbavSpC6gi4Xpn8/6kDKS4wcRa1djEaCpd5k7GcKTZZg9WYSPULfeRvFUEVPwQBHh7vdZpF/MO8jbROU5qD8L3QkLt1M83QSxUPnYP9H+Fn+2HtQrcblf9vj2BeBY0ueQL72VB72zvqwDAKfSRQyWAUyq/JB0ZlysgRpZyH7w3H4Fbmt4V+lyA1Vmw1wA9Nw2Wi3nypdk55iXluDA377eFy1Vh5TmHAIE59r7pxWGoZgtBL4SuGV2gaxTjfKVB2+rjWC38JaDtr2CaiJAQrY8SIeKPOd/D+VPTRnfcmxdAyyRtTBk8milyP0gKbWRU0REb3REyDI8KKn+oPhM73BzZhKZnigyWNxo47sld5avek9qns2OD+6iE5+DdW6FMyAk2sSwhQGTpXWxKH77o2QzUGJv8IYppJRrZE09eKScyHJB+46pcZRiI0oRfbcB3oGk1/a1MrRAOi/BhogeLFTGN164gv0r9c8lw3ntWZXp+rCJEzXDrxiIKUnfFAj20=
  app: protected-fjord-4731
  on:
    repo: a1510jy/rakuten_enpit_example
cache:
  directories:
  - vendor/bundle

